---
created:
  - 2024-11-26 18:29
aliases:
  - Rust crash course Error handling 2024-11-26
tags:
  - Programming/learning
language: rust
---
```meta-bind-button
label: Start adding topics
id: transcript
style: primary
actions:
  - type: command
    command: quickadd:choice:8e31af9f-9c45-478a-8752-70858a79703f

```
# ğŸ”¥ Rust crash course Error handling 2024-11-26 

---
## ğŸ“ƒNotes 
### Panic
When you want to throw an error you can use `panic` macro.

> Via an environment variable, you can also have Rust display the call stack

> By default, when a panic occurs the program startsÂ _unwinding_, which means Rust walks back up the stack and cleans up the data from each function it encounters.

> Â If in your project you need to make the resultant binary as small as possible, you can switch from unwinding to aborting upon a panic by addingÂ `panic = 'abort'`

> set theÂ `RUST_BACKTRACE`Â environment variable to get a backtrace of exactly what happened to cause the error.

### Result

> UsingÂ `match`Â works well enough, but it can be a bit verbose and doesnâ€™t always communicate intent well. TheÂ `Result<T, E>`Â type has many helper methods defined on it to do various, more specific tasks. TheÂ `unwrap`Â method is a shortcut method implemented just like theÂ `match`Â expression we wrote in Listing 9-4. If theÂ `Result`Â value is theÂ `Ok`Â variant,Â `unwrap`Â will return the value inside theÂ `Ok`. If theÂ `Result`Â is theÂ `Err`Â variant,Â `unwrap`Â will call theÂ `panic!`Â macro for us. Here is an example ofÂ `unwrap`Â in action:

> f we run this code without aÂ _hello.txt_Â file, weâ€™ll see an error message from theÂ `panic!`Â call that theÂ `unwrap`Â method makes

> Â theÂ `expect`Â method lets us also choose theÂ `panic!`Â error message. UsingÂ `expect`Â instead ofÂ `unwrap`Â and providing good error messages can convey your intent and make tracking down the source of a panic easier. The syntax ofÂ `expect`Â looks like this:

> This pattern of propagating errors is so common in Rust that Rust provides the question mark operatorÂ `?`Â to make this easier.

```rust
use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -> Result<String, io::Error> { 
  let mut username_file = File::open("hello.txt")?;
  let mut username = String::new();
  username_file.read_to_string(&mut username)?; 
  Ok(username)
}
```

> Â If the value of theÂ `Result`Â is anÂ `Ok`, the value inside theÂ `Ok`Â will get returned from this expression, and the program will continue. If the value is anÂ `Err`, theÂ `Err`Â will be returned from the whole function as if we had used theÂ `return`Â keyword so the error value gets propagated to the calling code.

> error values that have theÂ `?`Â operator called on them go through theÂ `from`Â function, defined in theÂ `From`Â trait in the standard library, which is used to convert values from one type into another. When theÂ `?`Â operator calls theÂ `from`Â function, the error type received is converted into the error type defined in the return type of the current function.

>TheÂ `?`Â operator follows theÂ `Result`Â value returned byÂ `File::open`, but thisÂ `main`Â function has the return type ofÂ `()`, notÂ `Result`. When we compile this code, we get the following error

>his error points out that weâ€™re only allowed to use theÂ `?`Â operator in a function that returnsÂ `Result`,Â `Option`, or another type that implementsÂ `FromResidual`.

> TheÂ `?`Â operator wonâ€™t automatically convert aÂ `Result`Â to anÂ `Option`Â or vice versa;

```rust
use std::eror::Error;
use std::fs::File;

fn main() -> Result<(), Box<dyn Error>> {
  let greeting_file = File::open("hello.txt");
  Ok(())
}
```

> TheÂ `Box<dyn Error>`Â type is aÂ _trait objec_



# ğŸ“¦References 
- [do rust lang org - Error Handling](https://doc.rust-lang.org/book/ch09-01-unrecoverable-errors-with-panic.html)